spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prod_fruit_shop
    username: prod_user
    password: p@55w0rd
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false